import HomePage from "@/Components/HomePage";

import "./globals.css";


export const metadata = {
  title: "Next js Blog WebSite",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <div className="">
      <HomePage />
    </div>
  );
}
